const CHATGPT_PROMPT_TEXT = process.env.REACT_APP_CHATGPT_PROMPT_TEXT;
const CHATGPT_API_KEY = process.env.REACT_APP_CHATGPT_API_KEY;
const CHATGPT_MAX_TOKENS = process.env.REACT_APP_CHATGPT_MAX_TOKENS;

export default {
  CHATGPT_PROMPT_TEXT,
  CHATGPT_API_KEY,
  CHATGPT_MAX_TOKENS,
};
